# Generated by Django 3.0.3 on 2020-03-16 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FineSystemapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='user',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
