# Generated by Django 3.0.3 on 2020-03-16 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FineSystemapp', '0002_auto_20200316_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='id',
        ),
        migrations.AlterField(
            model_name='login',
            name='Username',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Fine_apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rule', models.CharField(max_length=265)),
                ('Fine_Amount', models.IntegerField()),
                ('Date', models.DateTimeField()),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FineSystemapp.login')),
            ],
        ),
    ]
