# Generated by Django 3.0.3 on 2020-03-21 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FineSystemapp', '0006_rules_fine_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine_apply',
            name='Rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FineSystemapp.RULEs'),
        ),
    ]
