# Generated by Django 3.0.3 on 2020-03-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FineSystemapp', '0008_auto_20200321_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='id',
        ),
        migrations.AlterField(
            model_name='login',
            name='Username',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
