# Generated by Django 3.0.3 on 2020-03-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FineSystemapp', '0009_auto_20200321_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine_apply',
            name='Fine_Amount',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rules',
            name='Fine_amount',
            field=models.CharField(max_length=20),
        ),
    ]
