# Generated by Django 3.0.3 on 2020-03-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FineSystemapp', '0011_auto_20200321_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_fine',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
